##Testing R

Load libraries
```{r}
library(gplots)
library(ggplot2)
library(gridExtra)
library(grid)
library(likert)
library(ggnewscale)
library(caret)
library(pals)
library(yardstick)
```

Load data
```{r}
data <- read.csv("C:/Users/steem/Desktop/StudiesKTH/II2202 Research Methodology and Scientific Writing/SentimentAndStance/Data Analysis/dataset/output_test_regression_classes.csv")

##data <- read.csv("C:/Users/steem/Desktop/StudiesKTH/II2202 Research Methodology and Scientific Writing/SentimentAndStance/Data Analysis/dataset/output.csv")

data
```

Pre-process
```{r}
predicted_sentiment <- data$sentimentVader
predicted_stance <- data$StanceSVM


data$sentimentVader <- predicted_sentiment
data$StanceSVM <- predicted_stance
```

Visualization
```{r}
# Based on DanO's answer on https://stackoverflow.com/questions/61504970/ggplot2-heatmap-2-different-color-schemes-confusion-matrix-matches-in-differe but with several fixes and improvements
plot.plotWithDiagonalMarked <- function(confusionMatrix, xlabel, ylabel, xValueLabels, yValueLabels, valueOrdering) {
  yValueLabels = rev(yValueLabels) #y labels go from bottom to top, instead of the expected top to bottom
  confusionMatrix_diagonalMarked <- as.data.frame(confusionMatrix$table)
  confusionMatrix_diagonalMarked$diag <- confusionMatrix_diagonalMarked$Prediction == confusionMatrix_diagonalMarked$Reference # Get the diagonal
  # confusionMatrix_diagonalMarked[confusionMatrix_diagonalMarked$Freq == 0, ] <- NA # If an tile is empty, mark it is NA so we can give it another color (comma is there to prevent a weird crash https://stackoverflow.com/questions/51027983/r-error-from-nas-to-0-duplicate-subscripts-for-column-in-data-frame)
  confusionMatrix_diagonalMarked$Reference <- reverse.levels(confusionMatrix_diagonalMarked$Reference) # diagonal starts at top left
  confusionMatrix_diagonalMarked$ref_freq <- confusionMatrix_diagonalMarked$Freq * ifelse(confusionMatrix_diagonalMarked$diag, 1, -1) # flip sign for non-diagonal values
  # confusionMatrix_diagonalMarked$ref_freq <- scale(confusionMatrix_diagonalMarked$ref_freq) # normalize values
  confusionMatrix_diagonalMarked$ref_freq <- confusionMatrix_diagonalMarked$ref_freq + max(confusionMatrix_diagonalMarked$Freq) + min(confusionMatrix_diagonalMarked$Freq)  # This for some reason fixes the colour range not being scaled properly, found by experimentation
  print(confusionMatrix_diagonalMarked)
  # plotting the matrix
  confusionMatrix_diagonalMarked_plot <- ggplot(
            data = confusionMatrix_diagonalMarked,
            aes(x = Prediction, y = Reference, fill = Freq)) +
          xlab(xlabel) +
          ylab(ylabel) +
          geom_tile(
            data = confusionMatrix_diagonalMarked,
            aes(fill = ref_freq)) +
          scale_fill_gradientn(
             guide = FALSE,
             colours=c("red", "white", "#D6EAF8", "#2E86C1"),
             values=scales::rescale(c(-1, 0, 0.001, 1)),
             na.value="white") +
          geom_text(
             aes(label = Freq),
             color = 'black',
             size = 6) +
          scale_x_discrete(labels=xValueLabels, limits=valueOrdering, expand=c(0,0), position = "top") +
          scale_y_discrete(labels=yValueLabels, limits=rev(valueOrdering), expand=c(0,0)) +
          coord_equal() +
          theme_light() +
          theme(
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            legend.position = "none",
            panel.border = element_blank(),
            plot.background = element_blank(),
            axis.line = element_blank(),
            axis.text = element_text(size=20),
            axis.title= element_text(size=30, face="bold")
            )
  return(confusionMatrix_diagonalMarked_plot)
}
```

```{r}
sentimentValueLabels = c("Very Neg", "Negative", "Neutral", "Positive", "Very Pos")
stanceValueLabels = c("Strongly Against", "Againts", "Neutral", "Agree", "Strongly Agree")
valueOrdering = c("0", "1", "3", "4", "5")
```

EXPERIMENTS


Experiment 4) How much overlap is there between sentiment and stance?

```{r}
cat(100*sum(predicted_stance == predicted_sentiment) / length(predicted_stance),  "% accuracy", sep = '')

pred_sent_stance <- data.frame(
  Prediction = data$StanceSVM,
  Reference = data$sentimentVader
)

pred_sent_stance$Reference <- as.factor(pred_sent_stance$Reference)
pred_sent_stance$Prediction <- as.factor(pred_sent_stance$Prediction)

confusionMatrix <- caret::confusionMatrix(pred_sent_stance$Reference, pred_sent_stance$Prediction)

plot <- plot.plotWithDiagonalMarked(confusionMatrix, 'VADER sentiment', 'SVM Stance', sentimentValueLabels, stanceValueLabels, valueOrdering)
plot
ggsave("C:/Users/steem/Desktop/StudiesKTH/II2202 Research Methodology and Scientific Writing/SentimentAndStance/Data Analysis/images/PredictionSentimentStance5x5.png")
```

Experiment 5) How do values for sentiment map to values for stance (with bucket sizes of 0.2)?






